
define(function(require, exports, module){


    var data=[
        //登陆
        {
            url:"login/bindLogin",
            //默认参数
            data:{
                "userName":"",
                "password":"",
                "next_page":""
            },
            save:function(data){
                this.data=data
            }
        },
        //注册
        {
            url:"login/bindRegister",
            //默认参数
            data:{
                "userName":"",
                password:"",
                mobile:"",
                verifyCode:"",
                next_page:""
            },
            save:function(data){
                this.data=data
            }
        },
        //搜素课程
        {
            url:"dc/searchCourse",
            //默认参数
            data:{
                "query":"",
                sortField:"",
                from:0,
                size:6
            },
            init:function(){
                this.data.from=0
            },
            query:function(query){
                this.data.query=query
            },
            _next:function(){
                this.data.from+=this.data.size
            }
        },
        //课程分类
        {
            url:"dc/courseCategory",
            //默认参数
            data:{
                "parentId":-1
            },
            query:function(query){
                this.data.parentId=query
            }
        },
        //学习阶段
        {
            url:"target/getStages"
        },
        //课程分类元数据获取
        {
            url:"target/getLessonById",
            data:{
                id:657
            }
        },
        //兴趣与能力
        {
            url:"target/getInt"
        },
        //保存课程设置数据
        {
            url:"target/saveData",
            //默认参数
            data:{
                "stage":"",
                interest:"",
                target:""
            },
            save:function(data){
                this.data=data
            }
        },
        //保存课程设置数据
        {
            url:"conllect/save",
            //默认参数
            data:{
                "order":"1"
            },
            save:function(data){
                this.data=data
            }
        },
        //查看课程被收藏数
        {
            url:"conllect/getnumber",
            //默认参数
            data:{
                "productid":"002"
            },
            query:function(query){
                this.data.productid=query
            }
        },
        //查看用户收藏课程列表
        {
            url:"conllect/getconlist",
            //默认参数
            data:{
                "order":"1"
            },
            query:function(query){
                this.data.order=query
            },
            _next:function(query){
                this.data.order++
            }
        },
        //课程详情
        {
            url:"dc/courseDetail",
            //默认参数
            data:{
                "productId":1734
            },
            query:function(query){
                this.data.order=query
            }
        },
        //免费领课
        {
            url:"dc/takeFreeCourse",
            //默认参数
            data:{
                "productId":1734
            },
            query:function(query){
                this.data.order=query
            }
        },
        //微信支付
        {
            url:"dc/weixinPay",
            //默认参数
            data:{
                "productId":1734
            },
            query:function(query){
                this.data.order=query
            }
        },
        //获取个人信息接口
        {
            url:"myinfo/getinfo"
        },
        //查看课程被收藏数
        {
            url:"conllect/getnumber",
            //默认参数
            data:{
                "productid":"002"
            },
            query:function(query){
                this.data.productid=query
            }
        },
        //查看用户收藏课程列表
        {
            url:"conllect/getconlist",
            //默认参数
            data:{
                "order":"002"
            },
            query:function(query){
                this.data.order=query
            },
            _next:function(){
                this.data.order++
            }
        },
        //课程详情
        {
            url:"dc/courseDetail",
            //默认参数
            data:{
                "productId":"1734"
            },
            query:function(query){
                this.data.productId=query
            }
        },
        //免费领课
        {
            url:"dc/takeFreeCourse",
            //默认参数
            data:{
                "productId":"1734"
            },
            query:function(query){
                this.data.productId=query
            }
        },
        //微信支付
        {
            url:"dc/weixinPay",
            //默认参数
            data:{
                "productId":"1734"
            },
            query:function(query){
                this.data.productId=query
            }
        },
        //保存个人设置
        {
            url:"myinfo/saveinfo",
            //默认参数
            data:{
                "type":"1",
                "sex":"-1",
                "region":"",
                "realName":"",
                "mobile":"",
                "address":"",
                "email":""

            },
            save:function(data){
                this.data=data
            }
        },
        //取消课程收藏状态
        {
            url:"conllect/unsave",
            //默认参数
            data:{
                "productId":"1734"
            },
            query:function(query){
                this.data.productId=query
            }
        },
        //我的历史、现在、将要播放的课程
        {
            url:"dc/myCourse",
            //默认参数
            data:{
                period: -1,//-10,1//代表历史，今日，将要
                pageNo:"0",
                pageSize:"6"
            }
        },
        //找回密码--发送手机验证码
        {
            url:"fpwd/sendMobileCode",
            //默认参数
            data:{
                mobile:""
            }
        },
        //找回密码--发送手机验证码
        {
            url:"fpwd/sendMobileCode",
            //默认参数
            data:{
                mobile:""
            }
        },
        //找回密码--校验手机验证码
        {
            url:"fpwd/verifyCode",
            //默认参数
            data:{
                mobile:"",
                vcode:""
            }
        },
        //找回密码--校验手机验证码
        {
            url:"fpwd/verifyCode",
            //默认参数
            data:{
                mobile:"",
                vcode:""
            }
        },
        //找回密码--重置密码
        {
            url:"fpwd/findPwd",
            //默认参数
            data:{
                mobile:"",
                vcode:"",
                newPwd:""
            }
        },
        //获取用户信息
        {
            url:"login/getUserInfo"
        },
        //判断用户是否购买过某个课程
        {
            url:"dc/isBuy",
            data:{
                "productId":"1734"
            },
            query:function(query){
                this.data.productId=query
            }
        },
        //按照分类查询课程
        {
            url:"dc/listCourse",
            data:{
                "firstLevel":"",
                "secondLevel":"",
                "priceType":"-1",
                "from":"0",
                "pageSize":"6"
            }
        }
    ]

    module.exports=data

})
